# Generated by Django 5.1.7 on 2025-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='rights',
            field=models.CharField(default='NC', max_length=2),
        ),
    ]
