# Generated by Django 5.1.7 on 2025-04-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contactquery_alter_companyreg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactquery',
            old_name='date_sent',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='contactquery',
            name='is_read',
        ),
    ]
