# Generated by Django 5.1.7 on 2025-04-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_date_sent_contactquery_submitted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactQuery',
        ),
    ]
