# Generated by Django 5.1.7 on 2025-04-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contactquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactQuery',
        ),
    ]
