# Generated by Django 5.1.7 on 2025-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_contactquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
