# Generated by Django 5.1.7 on 2025-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
