# Generated by Django 5.1.7 on 2025-04-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userreg_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('qualification_required', models.CharField(max_length=100)),
                ('skills_required', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companyreg')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=12)),
                ('addrs', models.CharField(max_length=190)),
                ('skills', models.TextField()),
                ('highest_qualification', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobvacancy')),
            ],
        ),
    ]
