# Generated by Django 5.1.7 on 2025-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_jobvacancy_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='location',
            field=models.CharField(default=True, help_text='City, State or Remote/Hybrid', max_length=100),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='number_of_vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='responsibilities',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='salary_range',
            field=models.CharField(default=True, help_text="e.g., 3-5 LPA or 'Negotiable'", max_length=100),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='work_experience',
            field=models.CharField(default=True, help_text='e.g., 0-1 years, 2-3 years, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='qualification_required',
            field=models.CharField(help_text='e.g., B.Tech, BCA, MBA (comma-separated if multiple)', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='skills_required',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
    ]
