# Generated by Django 5.1.7 on 2025-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
