# Generated by Django 5.1.7 on 2025-04-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_jobapplication_interview_date_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2025, 5, 19)),
        ),
    ]
