# Generated by Django 5.1.7 on 2025-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_jobvacancy_last_date_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
