# Generated by Django 5.1.7 on 2025-04-20 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_jobvacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='addrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='pswrd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='uname',
            field=models.CharField(max_length=50),
        ),
    ]
