# Generated by Django 5.1.7 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_jobvacancy_last_date_to_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreg',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companyreg',
            name='contact_person',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='addrs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='location',
            field=models.CharField(default=True, help_text='City, State or Remote/Hybrid', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='salary_range',
            field=models.CharField(default=True, help_text="e.g., 3-5 LPA or 'Negotiable'", max_length=50),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='work_experience',
            field=models.CharField(default=True, help_text='e.g., 0-1 years, 2-3 years, etc.', max_length=50),
        ),
    ]
