# Generated by Django 5.1.7 on 2025-04-20 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_companyreg_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='last_date_to_apply',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='qualification_required',
            field=models.CharField(help_text='e.g., B.Tech, BCA, MBA (comma-separated if multiple)', max_length=50),
        ),
    ]
