# Generated by Django 5.1.7 on 2025-04-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_companyreg_user_jobapplication_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreg',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='user',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobvacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companyreg'),
        ),
    ]
